import SwiftUI

/// LiquidGlass Playground: Code Exporter
/// 
/// Instantly generates production-ready SwiftUI code from your playground configuration.
public struct CodeExporter {
    public static func export(cornerRadius: CGFloat, shadowRadius: CGFloat) -> String {
        return """
        // Generated by LiquidGlass Playground
        import SwiftUI
        
        struct MyGlassView: View {
            var body: some View {
                Text("Hello World")
                    .padding()
                    .background(.ultraThinMaterial)
                    .clipShape(RoundedRectangle(cornerRadius: \(cornerRadius)))
                    .shadow(radius: \(shadowRadius))
            }
        }
        """
    }
}
